version: "3.7"
services:

  solarflux:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: solarflux
    restart: always
    volumes:
    - ./config.json:/app/config.json:ro
